project_id = "akcxkwbqeehxvwhmrqbb"

[functions.send-help]
verify_jwt = false

[functions.upload-call-analysis]
verify_jwt = true

[functions.get-vapi-key]
verify_jwt = false

[functions.test-function]
verify_jwt = false